---
title: "combined-heatmaps"
author: "Lukáš Hejtmánek"
date: "30 3 2022"
output: html_document
---

```{r setup, include=FALSE}
library(fgu.avoidance)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
source("functions/visualisations.R")

knitr::opts_chunk$set(echo = FALSE)
```

```{r loading data runs 43 44}
data_pth <- "data/OTTER_raw_runs 43_44_final_normative_data/"
folders <- list.dirs(data_pth, full.names = FALSE, recursive = FALSE)

## Table prep ------
df_request <- as.data.frame(str_split(folders,"-", simplify = TRUE))
df_request <- df_request %>%
  mutate(across(everything(), str_trim)) %>%
  separate(V1, into=c("condition", "group"), sep = "\\s+") %>%
  separate(V3, into=c("analysis_1", "analysis_2"), sep="\\s\\+\\s",
           fill="left") %>%
  mutate(folder = list.dirs(data_pth, recursive = FALSE),
         average_heatmap = grepl("average heatmap", analysis_2),
         individual_analysis = !is.na(analysis_1))%>%
  unite(code, condition, group, remove=FALSE)

df_request <- df_request %>%
  filter(group == "handled",
         grepl("hab", condition))

files <- list.files(data_pth, recursive = TRUE, full.names = TRUE)
files <- files[grepl("//", files)]
files <- gsub(data_pth, "", files)

df_files4344 <- as.data.frame(str_split(files, "/", simplify = TRUE)) %>%
  select(-V1, folder = V2, file = V3) %>%
  mutate(filename = gsub(".CSV", "", file)) %>%
  separate(filename, into = c("run", "trial", "animal", "context"),
           sep = "_", remove = TRUE) %>%
  mutate(animal = gsub("rat[0]*", "animal_", animal),
         context = gsub("context", "", context),
         run = gsub("run", "", run))

all_data4344 <- list()
for(i in 1:nrow(df_request)){
  line <- df_request[i,]
  dat <- load_folder(line$folder)
  all_data4344[[line$condition]] <- dat
}

codingtables4344 <- list()
for(foldercode in names(all_data4344)){
  if("codingtable" %in% names(all_data4344[[foldercode]])){
    all_data4344[[foldercode]]$codingtable <- NULL
  }
  dat <- all_data4344[[foldercode]]
  out <- sapply(names(dat), function(x){return(list(animalcode = x,
                                             source = dat[[x]]$filepath))},
              simplify = FALSE, USE.NAMES = TRUE)
  codingtable <- data.frame(matrix(unlist(out),
                                    nrow = length(out),
                                    byrow = TRUE),
                             stringsAsFactors = FALSE)
  colnames(codingtable) <- c("animal", "source")
  codingtable <- codingtable %>%
    mutate(source = gsub(data_pth, "", source)) %>%
    separate(source, into = c("trail", "folder", "file"), sep = "/", remove = FALSE) %>%
    select(-trail)
  codingtables4344[[foldercode]]$codingtable <- codingtable
}
```

```{r loading data run 47}
data_pth <- "data/reveiw_run47/"
folders <- list.dirs(data_pth, full.names = FALSE, recursive = FALSE)

files <- list.files(data_pth, recursive = TRUE, full.names = TRUE)
files <- files[grepl("//", files)]
files <- gsub(data_pth, "", files)

df_files47 <- as.data.frame(str_split(files, "/", simplify = TRUE)) %>%
  select(-V1, folder = V2, file = V3) %>%
  mutate(filename = gsub(".CSV", "", file)) %>%
  separate(filename, into = c("trial", "animal", "context"),
           sep = "_", remove = TRUE) %>%
  mutate(animal = gsub("rat[0]*", "", animal),
         context = gsub("context", "", context),
         run = "47")

df_files47 <- df_files47 %>%
  filter(trial %in% c("hab1", "hab2", "hab3", "hab4"))

df_folders47 <- select(df_files47, folder, trial) %>%
  distinct()
all_data47 <- list()
for(i in 1:nrow(df_folders47)){
  line <- df_folders47[i, ]
  dat <- load_folder(file.path(data_pth, line$folder))
  all_data47[[line$trial]] <- dat
}

codingtables47 <- list()
for(foldercode in names(all_data47)){
  if("codingtable" %in% names(all_data47[[foldercode]])){
    all_data47[[foldercode]]$codingtable <- NULL
  }
  dat <- all_data47[[foldercode]]
  out <- sapply(names(dat), function(x){return(list(animalcode = x,
                                             source = dat[[x]]$filepath))},
              simplify = FALSE, USE.NAMES = TRUE)
  codingtable <- data.frame(matrix(unlist(out),
                                    nrow = length(out),
                                    byrow = TRUE),
                             stringsAsFactors = FALSE)
  colnames(codingtable) <- c("animal", "source")
  codingtable <- codingtable %>%
    mutate(source = gsub(data_pth, "", source)) %>%
    separate(source, into = c("trail", "folder", "file"), sep = "/", remove = FALSE) %>%
    select(-trail)
  codingtables47[[foldercode]]$codingtable <- codingtable
}
```

```{r warning=FALSE}
for(code in names(all_data4344)){
  temp4344 <- codingtables4344[[code]]$codingtable %>%
    left_join(df_files4344, by=c("folder", "file")) %>%
    select(-c(source, folder, file))
  
  temp47 <- codingtables47[[code]]$codingtable %>%
    left_join(df_files47, by=c("folder", "file")) %>%
    select(-c(source, folder, file))
  
  contextA4344 <- filter_animals(all_data4344[[code]],
                             temp4344$animal.x[temp4344$context == "A"])
  contextB4344 <- filter_animals(all_data4344[[code]],
                             temp4344$animal.x[temp4344$context == "B"])

  contextA47 <- filter_animals(all_data47[[code]],
                             temp47$animal.x[temp47$context == "A"])
  
  contextB47 <- filter_animals(all_data47[[code]],
                             temp47$animal.x[temp47$context == "B"])
  

  print(paper_heatmap(contextA4344, "A") + ggtitle(code, subtitle = "Context A run 43 44"))
  print(paper_heatmap(contextA47, "A") + ggtitle(code, subtitle = "Context A run 47"))
  contextA47 <- flip_x_positions(contextA47)
  print(paper_heatmap(contextA47, "A") + ggtitle(code, subtitle = "Context A run 47 flipped"))
  contextA <- append(contextA4344, contextA47)
  print(paper_heatmap(contextA, "A") + ggtitle(code, subtitle = "Context A combined"))
  
  print(paper_heatmap(contextB4344, "B") + ggtitle(code, subtitle = "Context B run 43 44"))
  print(paper_heatmap(contextB47, "B") + ggtitle(code, subtitle = "Context B run 47"))
  contextB47 <- flip_x_positions(contextB47)
  print(paper_heatmap(contextB47, "B") + ggtitle(code, subtitle = "Context B run 47 flipped"))
  contextB <- append(contextB4344, contextB47)
  print(paper_heatmap(contextB, "B") + ggtitle(code, subtitle = "Context B combined"))
}
```


